name: Puppeteer and Lighthouse

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm install
      - name: Run main.mjs
        run: node scripts/main.mjs
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Scripts-artifacts
          path: auto_*
